"""The trained policy, and exactly what a policy trained on synthetic dynamics is worth.

What this is
-------------
A real reinforcement-learned policy: PPO, trained under a PID-Lagrangian
constraint wrapper against constraints C1--C3, with the veto rate structurally
excluded from its reward (SI-6). Weights come from ``training/train_policy.py``
and load as a plain ``state_dict`` into :class:`~.network.PolicyNetwork`.

Unlike :class:`~.policies.KinematicPlaceholderPolicy`, this one has the
properties the threat model assumes: it can drift, it can be confidently wrong
in states it never saw, and its failures are not bounded by any structural
property of a control law. That is the point. Core-B's gates are designed
against a component that behaves like this, and until one existed they had never
been pointed at anything that could actually surprise them.

What it is not
---------------
**It is not trained against CARLA.** It is trained against the kinematic bicycle
model in ``training/environment.py`` -- the same family of motion the UKF
already assumes and the same limitation recorded for the twin's corpus. The
consequence is specific and must travel with any number produced from it:

* It **can** demonstrate that a learned policy drives the pipeline, that the
  gates evaluate genuinely learned commands, and that the Lagrangian wrapper
  moves the constraint costs it is supposed to move.
* It **cannot** support a false-positive or false-negative rate, because the
  distribution it was trained on and the distribution it is evaluated on are
  generated by the same equations. Nothing here is out-of-distribution in the
  sense the statistical gate is calibrated for.

Those claims need Stage 4 proper, against CARLA, which no macOS build supports.
Reported as such in the evidence ledger rather than quietly elided.

Why loading is strict
----------------------
``load_state_dict`` runs with ``strict=True`` and the checkpoint carries the
normalisers the features were built with. A policy loaded with a mismatched
feature scale does not raise; it produces plausible commands computed from
misscaled inputs, and the failure looks like poor tuning rather than a loading
bug. Refusing at construction is the only point where that is cheap to catch.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Final

import torch

from astra.kernel.enums import LayerId
from astra.kernel.errors import ConfigurationError
from astra.kernel.validation import require_positive
from astra.layers.l4_proposer.network import (
    PolicyNetwork,
    command_from_normalised,
    policy_features,
)

if TYPE_CHECKING:
    from collections.abc import Sequence
    from pathlib import Path

__all__ = ["LearnedPolicy", "PolicyCheckpoint"]

_REQUIRED_KEYS: Final[tuple[str, ...]] = (
    "weights",
    "command_dimension",
    "lane_half_width_m",
    "reference_speed_mps",
    "lateral_acceleration_limit_mps2",
    "channel_lower",
    "channel_upper",
)
"""Everything a checkpoint must carry to be loadable.

The three feature normalisers and the two channel-bound rows are in that list
because they are part of the policy, not part of its configuration. Change a
feature normaliser after training and every input the network sees is on a
different scale from the ones it learned on; change a channel bound and every
output means something else. Neither failure raises anything on its own."""


class PolicyCheckpoint:
    """A parsed policy checkpoint: weights plus the feature scales they assume."""

    __slots__ = (
        "channel_lower",
        "channel_upper",
        "command_dimension",
        "lane_half_width_m",
        "lateral_acceleration_limit_mps2",
        "reference_speed_mps",
        "weights",
    )

    def __init__(self, payload: dict[str, Any]) -> None:
        """Validate and unpack a checkpoint payload.

        Args:
            payload: The mapping written by the trainer.

        Raises:
            ConfigurationError: If a required key is missing.
            RangeViolationError: If a normaliser is not positive. A zero
                normaliser divides by zero into every feature; a negative one
                silently mirrors the policy's idea of which way is left.
        """
        missing = [key for key in _REQUIRED_KEYS if key not in payload]
        if missing:
            message = (
                f"policy checkpoint is missing {missing}; a checkpoint without its "
                f"feature normalisers cannot be loaded safely, because the network "
                f"would be fed features on a different scale from the ones it learned"
            )
            raise ConfigurationError(
                message, layer=LayerId.L4_CORE_A_CMDP, context={"missing": missing}
            )
        self.weights: dict[str, torch.Tensor] = payload["weights"]
        self.command_dimension = int(payload["command_dimension"])
        self.lane_half_width_m = float(payload["lane_half_width_m"])
        self.reference_speed_mps = float(payload["reference_speed_mps"])
        self.lateral_acceleration_limit_mps2 = float(payload["lateral_acceleration_limit_mps2"])
        self.channel_lower = tuple(float(value) for value in payload["channel_lower"])
        self.channel_upper = tuple(float(value) for value in payload["channel_upper"])

        widths = {len(self.channel_lower), len(self.channel_upper), self.command_dimension}
        if len(widths) != 1:
            message = (
                f"checkpoint channel bounds do not match its command dimension: "
                f"lower={len(self.channel_lower)}, upper={len(self.channel_upper)}, "
                f"command_dimension={self.command_dimension}"
            )
            raise ConfigurationError(
                message, layer=LayerId.L4_CORE_A_CMDP, context={"widths": sorted(widths)}
            )
        for low, high in zip(self.channel_lower, self.channel_upper, strict=True):
            if not high > low:
                message = (
                    f"checkpoint channel bounds must be ordered, got lower={low} "
                    f"upper={high}; a degenerate channel maps every normalised action "
                    f"to the same command"
                )
                raise ConfigurationError(message, layer=LayerId.L4_CORE_A_CMDP)

        require_positive(
            self.command_dimension,
            name="checkpoint.command_dimension",
            layer=LayerId.L4_CORE_A_CMDP,
        )
        for name in (
            "lane_half_width_m",
            "reference_speed_mps",
            "lateral_acceleration_limit_mps2",
        ):
            require_positive(
                getattr(self, name), name=f"checkpoint.{name}", layer=LayerId.L4_CORE_A_CMDP
            )


class LearnedPolicy:
    """A trained actor. Satisfies :class:`~.proposer.Policy`.

    Inference is deterministic: the Gaussian policy's mean, with no sampling.
    Exploration belongs to training. A stochastic proposer would make the
    evidence log non-reproducible for reasons unrelated to the vehicle's
    situation, and replay -- which the architecture requires to be exact --
    would stop being a check on anything.
    """

    __slots__ = ("_checkpoint", "_network")

    def __init__(self, checkpoint: PolicyCheckpoint) -> None:
        """Build the policy from a parsed checkpoint.

        Args:
            checkpoint: The weights and the feature scales they were trained at.

        Raises:
            ConfigurationError: If the weights do not fit the architecture.
        """
        network = PolicyNetwork(command_dimension=checkpoint.command_dimension)
        try:
            network.load_state_dict(checkpoint.weights, strict=True)
        except (RuntimeError, KeyError) as error:
            message = (
                f"policy checkpoint does not fit PolicyNetwork: {error}; loading it "
                f"loosely would produce a partly-initialised actor that still returns "
                f"plausible commands"
            )
            raise ConfigurationError(message, layer=LayerId.L4_CORE_A_CMDP) from error
        network.eval()
        self._network = network
        self._checkpoint = checkpoint

    @classmethod
    def load(cls, path: Path) -> LearnedPolicy:
        """Load a policy from a checkpoint file.

        Args:
            path: The checkpoint written by ``training/train_policy.py``.

        Returns:
            The loaded policy.

        Raises:
            ConfigurationError: If the file is absent, unreadable, or not a
                well-formed checkpoint.
        """
        if not path.exists():
            message = (
                f"no policy checkpoint at {path}; train one with "
                f"`python training/train_policy.py --out {path}`"
            )
            raise ConfigurationError(
                message, layer=LayerId.L4_CORE_A_CMDP, context={"path": str(path)}
            )
        try:
            payload = torch.load(path, map_location="cpu", weights_only=True)
        except Exception as error:
            message = f"policy checkpoint at {path} could not be read: {error}"
            raise ConfigurationError(
                message, layer=LayerId.L4_CORE_A_CMDP, context={"path": str(path)}
            ) from error
        if not isinstance(payload, dict):
            message = f"policy checkpoint at {path} is not a mapping, got {type(payload).__name__}"
            raise ConfigurationError(
                message, layer=LayerId.L4_CORE_A_CMDP, context={"path": str(path)}
            )
        return cls(PolicyCheckpoint(payload))

    def act(self, observation: Sequence[float]) -> Sequence[float]:
        """Return the command vector for one observation.

        Args:
            observation: ``(px, py, v, psi, a_lat, TI)``.

        Returns:
            The command mean, one value per actuation channel. Deliberately not
            clamped to the actuation space: see
            :func:`~.network.command_from_normalised`.
        """
        features = policy_features(
            observation,
            lane_half_width_m=self._checkpoint.lane_half_width_m,
            reference_speed_mps=self._checkpoint.reference_speed_mps,
            lateral_acceleration_limit_mps2=(self._checkpoint.lateral_acceleration_limit_mps2),
        )
        with torch.no_grad():
            batch = torch.tensor([features], dtype=torch.float32)
            normalised = [float(value) for value in self._network(batch)[0]]
        return command_from_normalised(
            normalised,
            lower=self._checkpoint.channel_lower,
            upper=self._checkpoint.channel_upper,
        )
